/* Auto-generated by genmsg_cpp for file /home/overkill/devel/ros/Gen2_Platforms/gen2_drivers/gen2_motor_driver/msg/drive_msg.msg */
#ifndef GEN2_MOTOR_DRIVER_MESSAGE_DRIVE_MSG_H
#define GEN2_MOTOR_DRIVER_MESSAGE_DRIVE_MSG_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"


namespace gen2_motor_driver
{
template <class ContainerAllocator>
struct drive_msg_ : public ros::Message
{
  typedef drive_msg_<ContainerAllocator> Type;

  drive_msg_()
  : left_pwm(0)
  , right_pwm(0)
  , left_dir(false)
  , right_dir(false)
  {
  }

  drive_msg_(const ContainerAllocator& _alloc)
  : left_pwm(0)
  , right_pwm(0)
  , left_dir(false)
  , right_dir(false)
  {
  }

  typedef int32_t _left_pwm_type;
  int32_t left_pwm;

  typedef int32_t _right_pwm_type;
  int32_t right_pwm;

  typedef uint8_t _left_dir_type;
  uint8_t left_dir;

  typedef uint8_t _right_dir_type;
  uint8_t right_dir;


private:
  static const char* __s_getDataType_() { return "gen2_motor_driver/drive_msg"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "ee8af9d8d361abd230a87aebf4810eb3"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "\n\
int32 left_pwm\n\
int32 right_pwm\n\
bool left_dir\n\
bool right_dir\n\
\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, left_pwm);
    ros::serialization::serialize(stream, right_pwm);
    ros::serialization::serialize(stream, left_dir);
    ros::serialization::serialize(stream, right_dir);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, left_pwm);
    ros::serialization::deserialize(stream, right_pwm);
    ros::serialization::deserialize(stream, left_dir);
    ros::serialization::deserialize(stream, right_dir);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(left_pwm);
    size += ros::serialization::serializationLength(right_pwm);
    size += ros::serialization::serializationLength(left_dir);
    size += ros::serialization::serializationLength(right_dir);
    return size;
  }

  typedef boost::shared_ptr< ::gen2_motor_driver::drive_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gen2_motor_driver::drive_msg_<ContainerAllocator>  const> ConstPtr;
}; // struct drive_msg
typedef  ::gen2_motor_driver::drive_msg_<std::allocator<void> > drive_msg;

typedef boost::shared_ptr< ::gen2_motor_driver::drive_msg> drive_msgPtr;
typedef boost::shared_ptr< ::gen2_motor_driver::drive_msg const> drive_msgConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::gen2_motor_driver::drive_msg_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::gen2_motor_driver::drive_msg_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace gen2_motor_driver

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::gen2_motor_driver::drive_msg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ee8af9d8d361abd230a87aebf4810eb3";
  }

  static const char* value(const  ::gen2_motor_driver::drive_msg_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xee8af9d8d361abd2ULL;
  static const uint64_t static_value2 = 0x30a87aebf4810eb3ULL;
};

template<class ContainerAllocator>
struct DataType< ::gen2_motor_driver::drive_msg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "gen2_motor_driver/drive_msg";
  }

  static const char* value(const  ::gen2_motor_driver::drive_msg_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::gen2_motor_driver::drive_msg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
int32 left_pwm\n\
int32 right_pwm\n\
bool left_dir\n\
bool right_dir\n\
\n\
\n\
";
  }

  static const char* value(const  ::gen2_motor_driver::drive_msg_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::gen2_motor_driver::drive_msg_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::gen2_motor_driver::drive_msg_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.left_pwm);
    stream.next(m.right_pwm);
    stream.next(m.left_dir);
    stream.next(m.right_dir);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct drive_msg_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gen2_motor_driver::drive_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::gen2_motor_driver::drive_msg_<ContainerAllocator> & v) 
  {
    s << indent << "left_pwm: ";
    Printer<int32_t>::stream(s, indent + "  ", v.left_pwm);
    s << indent << "right_pwm: ";
    Printer<int32_t>::stream(s, indent + "  ", v.right_pwm);
    s << indent << "left_dir: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.left_dir);
    s << indent << "right_dir: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.right_dir);
  }
};


} // namespace message_operations
} // namespace ros

#endif // GEN2_MOTOR_DRIVER_MESSAGE_DRIVE_MSG_H

