/* Auto-generated by genmsg_cpp for file /home/loud/devel/ros/Gen2_Platforms/gen2_drivers/gen2_motor_driver/msg/pid_plot.msg */
#ifndef GEN2_MOTOR_DRIVER_MESSAGE_PID_PLOT_H
#define GEN2_MOTOR_DRIVER_MESSAGE_PID_PLOT_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"


namespace gen2_motor_driver
{
template <class ContainerAllocator>
struct pid_plot_ : public ros::Message
{
  typedef pid_plot_<ContainerAllocator> Type;

  pid_plot_()
  : left_vel(0.0)
  , right_vel(0.0)
  {
  }

  pid_plot_(const ContainerAllocator& _alloc)
  : left_vel(0.0)
  , right_vel(0.0)
  {
  }

  typedef float _left_vel_type;
  float left_vel;

  typedef float _right_vel_type;
  float right_vel;


private:
  static const char* __s_getDataType_() { return "gen2_motor_driver/pid_plot"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "74ad8f7ea4d888606e4f41069cec47ff"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "float32 left_vel\n\
float32 right_vel\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, left_vel);
    ros::serialization::serialize(stream, right_vel);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, left_vel);
    ros::serialization::deserialize(stream, right_vel);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(left_vel);
    size += ros::serialization::serializationLength(right_vel);
    return size;
  }

  typedef boost::shared_ptr< ::gen2_motor_driver::pid_plot_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gen2_motor_driver::pid_plot_<ContainerAllocator>  const> ConstPtr;
}; // struct pid_plot
typedef  ::gen2_motor_driver::pid_plot_<std::allocator<void> > pid_plot;

typedef boost::shared_ptr< ::gen2_motor_driver::pid_plot> pid_plotPtr;
typedef boost::shared_ptr< ::gen2_motor_driver::pid_plot const> pid_plotConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::gen2_motor_driver::pid_plot_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::gen2_motor_driver::pid_plot_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace gen2_motor_driver

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::gen2_motor_driver::pid_plot_<ContainerAllocator> > {
  static const char* value() 
  {
    return "74ad8f7ea4d888606e4f41069cec47ff";
  }

  static const char* value(const  ::gen2_motor_driver::pid_plot_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x74ad8f7ea4d88860ULL;
  static const uint64_t static_value2 = 0x6e4f41069cec47ffULL;
};

template<class ContainerAllocator>
struct DataType< ::gen2_motor_driver::pid_plot_<ContainerAllocator> > {
  static const char* value() 
  {
    return "gen2_motor_driver/pid_plot";
  }

  static const char* value(const  ::gen2_motor_driver::pid_plot_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::gen2_motor_driver::pid_plot_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32 left_vel\n\
float32 right_vel\n\
\n\
";
  }

  static const char* value(const  ::gen2_motor_driver::pid_plot_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::gen2_motor_driver::pid_plot_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::gen2_motor_driver::pid_plot_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.left_vel);
    stream.next(m.right_vel);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct pid_plot_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gen2_motor_driver::pid_plot_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::gen2_motor_driver::pid_plot_<ContainerAllocator> & v) 
  {
    s << indent << "left_vel: ";
    Printer<float>::stream(s, indent + "  ", v.left_vel);
    s << indent << "right_vel: ";
    Printer<float>::stream(s, indent + "  ", v.right_vel);
  }
};


} // namespace message_operations
} // namespace ros

#endif // GEN2_MOTOR_DRIVER_MESSAGE_PID_PLOT_H

